### Exercici 1
#### Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [4]:
import numpy as np
from numpy import random

# defineixo array

def array():
    array = random.randint(100, size=(6))
    return(array)

# comprobo dimensió i faig resum estadístic

def resum(arr):
    if arr.ndim != 1:     
        print('error')
    else:
        promig = np.mean(arr)
        mediana = np.median(arr)
        minim = np.min(arr)
        maxim = np.max(arr)
        desv = np.std(arr)
        print('el promig és:',promig,'la mediana és:',mediana,'el minim és:',minim,'el maxim és:',maxim,'i la desviació típica és:',desv,)

# crido funcions

arr = array()
print(arr)     
resum(arr)

[95 81 52 91 70 64]
el promig és: 75.5 la mediana és: 75.5 el minim és: 52 el maxim és: 95 i la desviació típica és: 15.0858653491715


In [13]:
import numpy as np
from numpy import random

# defineixo array de més de 1 D per forçar error

arr = np.array([[2,4],[6,8]])

# comprobo dimensió i faig resum estadístic

def resum(arr):
    if arr.ndim != 1:     
        print('error')
    else:
        promig = np.mean(arr)
        mediana = np.median(arr)
        minim = np.min(arr)
        maxim = np.max(arr)
        print('el promig és:',promig,'la mediana és:',mediana,'el minim és:',minim,'el maxim és:',maxim)

# crido funcions

resum(arr)

error


### Exercici 2
#### Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [2]:
from numpy import random

# demano el número del quadrat

n = int(input("Introdueix un número: "))

# faig la matriu

def matriu(n):
    quadrat = random.randint(100, size=(n,n))
    print(quadrat)

# crido la matriu

matriu(n)

Introdueix un número: 3
[[78 35  8]
 [ 0 86 87]
 [92 32 28]]


### Exercici 3
#### Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [3]:
from numpy import random
import numpy as np

# demano dades

n = int(input("Introdueix número files: " ))
m = int(input("Introdueix número columnes: "))

# omplo la matriu amb números aleatoris

quadrat = random.randint(100, size=(n,m))
print(quadrat)

# defineixo funció

def sumes(n,m,matriu):
    
    suma_files = []
    
    for n in quadrat:
        suma_files.append(sum(n))
    print('el total per fila és',suma_files)
    
    suma_columnes = []
    quadrat_invers = np.transpose(quadrat)
    for m in quadrat_invers:
        suma_columnes.append(sum(m))
    print('el total per columna és',suma_columnes)

# crido funció

sumes(n,m,quadrat)

Introdueix número files: 2
Introdueix número columnes: 4
[[23 60 23 24]
 [ 2 64  6  9]]
el total per fila és [130, 81]
el total per columna és [25, 124, 29, 33]


### Exercici 4
#### Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [10]:
import numpy as np

# defineixo dues arrays aleatòries:

x = np.random.randint(100, size=(20))
y = np.random.randint(100, size=(20))

# defineixo funció de coeficient de correlació:

def coef_corr(x,y):
    mean_x = x.mean()
    mean_y = y.mean()
    num = np.sum((x-mean_x)*(y- mean_y))
    den = np.sqrt(np.sum(np.power(x-mean_x, 2)) * np.sum(np.power(y-mean_y, 2)))
    coef = num/den
    return coef

# crido funció y comprobo amb la matriu

coef_corr_1 = coef_corr(x,y)
print('el coeficient de correlació és :',coef_corr_1)
pearsons_coefficient = np.corrcoef(x,y)
print('comprovem amb la matriu: \n',pearsons_coefficient)

el coeficient de correlació és : -0.21176523722750193
comprovem amb la matriu: 
 [[ 1.         -0.21176524]
 [-0.21176524  1.        ]]
